package qa.tonykid.addressbook;// Generated by Selenium IDE

//import org.junit.Test;

import org.testng.annotations.Test;

public class GroupCreationTest extends TestBase{


    @Test
    public void testGroupCreation() {

        goToGroupPage();
        initGroupCreation();
        fillGroupForm(new GroupData("test1", "test2", "test3"));
        submiGroupCreation();
        returnToGroupPage();
    }

}
